### ISSUE TITLE
Implement missing analytics tracking

### ISSUE THREAD

**Issue by radeklat** [mbarta/SmartContactReminder#4]
- [ ] **Category:** settings, **Action:** category_added, **Label:** category name
- [ ] **Category:** settings, **Action:** category_removed, **Label:** category name
- [ ] **Category:** settings, **Action:** category_changed, **Label:** old category name, **Custom dimension:** New category value
- [ ] **Category:** settings, **Action:** backup, **Label:** true if succeeded, false otherwise
- [ ] **Category:** settings, **Action:** restore, **Label:** true if succeeded, false otherwise
- [ ] **Category:** main_menu, **Action:** show_app_guide
- [ ] **Category:** main_menu, **Action:** faq
